name: Check dist

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  check-dist:
    name: Check dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, open a pull request:
      - uses: peter-evans/create-pull-request@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          add-paths: |
            dist/index.js
            dist/index.js.map
            dist/licenses.txt
            dist/sourcemap-register.js
          commit-message: Update dist
          committer: Wen Kokke <wenkokke@noreply.users.github.com>
          branch: update-dist
          delete-branch: true
          branch-suffix: timestamp
          title: Update dist
          body: |
            Automatic pull request to update dist created by
            [check-dist.yml](.github/workflows/check-dist.yml).
          labels: dist
          assignees: wenkokke
