name: setup

on:
  push:
    branches: ['main']
    paths: ['**.ts', '**.js', '**.json', '**.yml']

  pull_request:
    branches: ['main']
    paths: ['**.ts', '**.js', '**.json', '**.yml']
    types: [opened, synchronize, reopened]

jobs:
  check-dist:
    uses: ./.github/workflows/check-dist.yml

  setup-latest:
    needs: [check-dist]
    uses: ./.github/workflows/setup-latest.yml

  setup-legacy:
    needs: [check-dist]
    uses: ./.github/workflows/setup-legacy.yml

  setup-agda-stdlib-default:
    needs: [check-dist]
    uses: ./.github/workflows/setup-agda-stdlib-default.yml

  setup-libraries:
    needs: [check-dist]
    uses: ./.github/workflows/setup-libraries.yml

  release:
    if: ${{ github.event_name == 'push' }}
    needs: [check-dist, setup-latest, setup-legacy, setup-libraries]
    uses: ./.github/workflows/release.yml
